### ISSUE TITLE
SEAL version for building this project.

### ISSUE THREAD

**Issue by whcjimmy** [MarwanNour/SEAL-FYP-Logistic-Regression#2]
Hi, 

I am recently trying to build this project.

I've tested SEAL 3.5.0 and 3.5.8, but both failed for the same reason.

May I ask which SEAL do you use?

Thanks.

![螢幕擷取畫面 2020-12-30 141545](https://user-images.githubusercontent.com/4002046/103334495-7bfde800-4aac-11eb-8ffd-bb9744dcc8e5.png)

**Comment by whcjimmy** [comment]
I successfully built with SEAL version 3.4.5.

**Comment by MarwanNour** [comment]
@whcjimmy Hello, thank you for your input. I forgot to add the version I used. I will update the readme accordingly.
