### ISSUE TITLE
Logistic Regression with BFV scheme

### ISSUE THREAD

**Issue by huyvu1404** [MarwanNour/SEAL-FYP-Logistic-Regression#7]
Is it possible to implement Lr model using BFV scheme. Can you give me some suggestions? Thank you.

**Comment by MarwanNour** [comment]
From what I remember, it is possible to implement LR model with BFV, however:

- you will need to find workarounds to avoid integer overflow (computationally costly)
- you have a "noise budget" which will affect the number of possible multiplications. The larger the ciphertext, the bigger the consumption of the noise budget so you will also have to find some preprocessing methods before encrypting it.

I'm sorry I can't provided you with a full answer as I haven't touched this repository in quite some time.
